name: Build grassh

on:
  push:

jobs:
  windows:
    runs-on: windows-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Install yq
        run: curl.exe -o C:\Windows\System32\yq.exe -L https://github.com/mikefarah/yq/releases/latest/download/yq_windows_amd64.exe
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter build windows
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-windows
          path: Release/

  linux:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-linux
          path: Release/
      

  macos:
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
          flutter-version-file: pubspec.yaml
      - run: flutter build macos
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: grassh-macos
          path: Release/
